### ISSUE TITLE
Inherited events don't have a type.

### ISSUE THREAD

**Issue by PaulHMason** [open-wc/custom-elements-manifest#128]
I'm not sure it this is intentional or not, but inherited events don't have an inherited type like methods and fields - it would be useful for events to also have the type.

Also, CSS properties aren't inherited - not sure if this is intentional either.

**Comment by PaulHMason** [comment]
Hmmm - I don't think the first part is an issue, it seems you get the event type from the actually usage, not the JSDoc comment.

**Comment by thepassle** [comment]
This actually seems to be working as the schema expects it, since `CssCustomProperty` doesn't have a `inheritedFrom` field.

However, I think we should add the `inheritedFrom` field to the `CssCustomProperty` doc. Could you create an issue on the schema repository to discuss it there and adopt it in the schema?  https://github.com/webcomponents/custom-elements-manifest/issues
