### ISSUE TITLE
`TypeError` when dispatching custom event with no type argument

### ISSUE THREAD

**Issue by mihar-22** [open-wc/custom-elements-manifest#34]
## Description

As the reproduction showcases the analyzer will fail if the dispatched custom event has no type argument. There are occasionally cases where no type is required, see this [example](https://github.com/mihar-22/vds-player/blob/migrate-to-js/src/media/media.events.js).

**Error thrown location:** [ERROR](https://github.com/open-wc/custom-elements-manifest/blob/master/packages/analyzer/src/features/analyse-phase/creators/createClass.js#L146-L180)
**Reproduction Link:** [REPRODUCTION](https://custom-elements-manifest.netlify.app/?source=CmltcG9ydCB7IExpdEVsZW1lbnQgfSBmcm9tICdsaXQnOwoKLyoqCiAqIFNvbWUgaW5mb3JtYXRpb24gaGVyZS4KICovCmNsYXNzIE15Q3VzdG9tRXZlbnQgZXh0ZW5kcyBDdXN0b21FdmVudCB7CiAgY29uc3RydWN0b3IoZXZlbnRJbml0KSB7CiAgICBzdXBlcignbXktY3VzdG9tLWV2ZW50JywgZXZlbnRJbml0KTsKICB9Cn0KCmV4cG9ydCBjbGFzcyBNeUVsZW1lbnQgZXh0ZW5kcyBMaXRFbGVtZW50IHsKICBzdGF0aWMgZ2V0IHByb3BlcnRpZXMoKSB7CiAgICByZXR1cm4gewogICAgICBmb286IHsgdHlwZTogU3RyaW5nIH0KICAgIH0KICB9CgogIGNvbnN0cnVjdG9yKCkgewogICAgc3VwZXIoKTsKICAgIHRoaXMuZm9vID0gJ2hlbGxvJzsKICB9CgogIG15TWV0aG9kKCkgewogICAgICAvLyBGQUlMUyBIRVJFIGJlY2F1c2Ugbm8gYHR5cGVgIGFyZ3VtZW50IGlzIGJlaW5nIHBhc3NlZCB0byBgTXlDdXN0b21FdmVudGAuCiAgICAgIHRoaXMuZGlzcGF0Y2hFdmVudChuZXcgTXlDdXN0b21FdmVudCgpKTsKICB9Cn0K&library=litelement)

## Solution

Preferably the analyzer will go one step beyond and analyze the event if it's a `CustomEvent`. This includes collecting documentation from the class declaration, and checking the `super(...)` call for a `type` argument.

## Error

![image](https://user-images.githubusercontent.com/14304599/122693673-21d12900-d27e-11eb-935f-245be5fb5cf5.png)

**Comment by thepassle** [comment]
Events are a bit tricky in the sense that many people will have different ways of writing them. Currently in core, event discovery is fairly basic (it handles CustomEvent/Event, and JSDoc events annotated above a class the event is fired from).

I've added some safeguards around the bit where we try to get the `eventName` though, because it shouldnt crash on that.

I think there's room for improvement on event discovery for core, but I'll have to think on how to approach it a bit more in a generic way, for now I'd recommend you to either use JSDoc on your class to supplement the event information, or write a custom plugin that handles the events.

You can use the `collectPhase` to find all events throughout your modules, and the `analyzePhase` to discover `dispatchEvent` calls, and match them to the events found in the `collectPhase`

The error has been fixed in v0.3.2

**Comment by mihar-22** [comment]
Cool thanks @thepassle!
